//
//  This CSharp output file generated by Gardens Point LEX
//  Gardens Point LEX (GPLEX) is Copyright (c) John Gough, QUT 2006-2014.
//  Output produced by GPLEX is the property of the user.
//  See accompanying file GPLEXcopyright.rtf.
//
//  GPLEX Version:  1.2.2
//  Machine:  DESKTOP-EC2OMEU
//  DateTime: 1/30/2020 1:44:01 AM
//  UserName: honey
//  GPLEX input file <gplex.lex - 1/30/2020 12:29:45 AM>
//  GPLEX frame file <embedded resource>
//
//  Option settings: unicode, verbose, parser, stack, minimize
//  Option settings: classes, compressMap, compressNext, persistBuffer, noEmbedBuffers
//  Fallback code page: Raw 8-bit binary
//

//
// Revised backup code
// Version 1.2.1 of 24-June-2013
//
//
#define BACKUP
#define LEFTANCHORS
#define STACK
#define PERSIST

using System;
using System.IO;
using System.Text;
using System.Globalization;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Diagnostics.CodeAnalysis;

using QUT.GplexBuffers;
using System.Collections;
using QUT.Gplex.Parser;

namespace QUT.Gplex.Lexer
{   
    /// <summary>
    /// Summary Canonical example of GPLEX automaton
    /// </summary>
    
#if STANDALONE
    //
    // These are the dummy declarations for stand-alone GPLEX applications
    // normally these declarations would come from the parser.
    // If you declare /noparser, or %option noparser then you get this.
    //

     internal enum Tokens
    { 
      EOF = 0, maxParseToken = int.MaxValue 
      // must have at least these two, values are almost arbitrary
    }

     internal abstract class ScanBase
    {
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yylex")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yylex")]
        public abstract int yylex();

        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yywrap")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yywrap")]
        protected virtual bool yywrap() { return true; }

#if BABEL
        protected abstract int CurrentSc { get; set; }
        // EolState is the 32-bit of state data persisted at 
        // the end of each line for Visual Studio colorization.  
        // The default is to return CurrentSc.  You must override
        // this if you want more complicated behavior.
        public virtual int EolState { 
            get { return CurrentSc; }
            set { CurrentSc = value; } 
        }
    }
    
     internal interface IColorScan
    {
        void SetSource(string source, int offset);
        int GetNext(ref int state, out int start, out int end);
#endif // BABEL
    }

#endif // STANDALONE
    
    // If the compiler can't find the scanner base class maybe you
    // need to run GPPG with the /gplex option, or GPLEX with /noparser
#if BABEL
     internal sealed partial class Scanner : ScanBase, IColorScan
    {
        private ScanBuff buffer;
        int currentScOrd;  // start condition ordinal
        
        protected override int CurrentSc 
        {
             // The current start state is a property
             // to try to avoid the user error of setting
             // scState but forgetting to update the FSA
             // start state "currentStart"
             //
             get { return currentScOrd; }  // i.e. return YY_START;
             set { currentScOrd = value;   // i.e. BEGIN(value);
                   currentStart = startState[value]; }
        }
#else  // BABEL
     internal sealed partial class Scanner : ScanBase
    {
        private ScanBuff buffer;
        int currentScOrd;  // start condition ordinal
#endif // BABEL
        
        /// <summary>
        /// The input buffer for this scanner.
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ScanBuff Buffer { get { return buffer; } }
        
        private static int GetMaxParseToken() {
     System.Reflection.FieldInfo f = typeof(Tokens).GetField("maxParseToken");
            return (f == null ? int.MaxValue : (int)f.GetValue(null));
        }
        
        static int parserMax = GetMaxParseToken();
        
        enum Result {accept, noMatch, contextFound};

        const int maxAccept = 132;
        const int initial = 133;
        const int eofNum = 0;
        const int goStart = -1;
        const int INITIAL = 0;
        const int SKIP = 1;
        const int RULES = 2;
        const int UCODE = 3;
        const int BCODE = 4;
        const int LCODE = 5;
        const int INDNT = 6;
        const int CMMNT = 7;
        const int SMACT = 8;
        const int XPEOL = 9;
        const int REGEX = 10;
        const int NMLST = 11;
        const int SPACE = 12;
        const int VRBTM = 13;
        const int PRGRP = 14;

#region user code
/* 
 *  gplex.lex file, Version 1.2.1 including charset operators {-}, {+}, {*}
 *
 *  Expected file format is Unicode. In the event that no 
 *  byte order mark prefix is found, revert to raw bytes.
 */
#endregion user code

        int state;
        int currentStart = startState[0];
        int code;      // last code read
        int cCol;      // column number of code
        int lNum;      // current line number
        //
        // The following instance variables are used, among other
        // things, for constructing the yylloc location objects.
        //
        int tokPos;        // buffer position at start of token
        int tokCol;        // zero-based column number at start of token
        int tokLin;        // line number at start of token
        int tokEPos;       // buffer position at end of token
        int tokECol;       // column number at end of token
        int tokELin;       // line number at end of token
        string tokTxt;     // lazily constructed text of token
#if STACK          
        private Stack<int> scStack = new Stack<int>();
#endif // STACK

#region ScannerTables
    struct Table {
        public int min; public int rng; public int dflt;
        public short[] nxt;
        public Table(int m, int x, int d, short[] n) {
            min = m; rng = x; dflt = d; nxt = n;
        }
    };

    static int[] startState = new int[] {133, 136, 138, 145, 166, 168, 
        145, 69, 171, 173, 175, 188, 190, 192, 194, 0};

   static int[] anchorState = new int[] {134, 137, 139, 146, 167, 169, 
        170, 70, 172, 174, 176, 189, 191, 193, 195, 0};

#region CompressedCharacterMap
    //
    // There are 40 equivalence classes
    // There are 2 character sequence regions
    // There are 1 tables, 126 entries
    // There are 1 runs, 0 singletons
    // Decision tree depth is 1
    //
    static sbyte[] mapC0 = new sbyte[126] {
/*     '\0' */ 14, 24, 24, 24, 24, 24, 24, 14, 14, 3, 0, 14, 14, 4, 24, 24, 
/*   '\x10' */ 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 
/*   '\x20' */ 17, 29, 16, 27, 24, 7, 27, 31, 34, 35, 9, 26, 12, 25, 33, 1, 
/*      '0' */ 19, 19, 19, 19, 19, 19, 19, 19, 6, 6, 27, 32, 30, 28, 13, 27, 
/*      '@' */ 8, 21, 21, 21, 21, 36, 38, 5, 5, 5, 5, 5, 5, 5, 5, 37, 
/*      'P' */ 5, 5, 5, 5, 5, 23, 5, 5, 5, 5, 5, 2, 15, 18, 24, 5, 
/*      '`' */ 24, 21, 21, 21, 21, 21, 21, 5, 5, 5, 5, 5, 5, 5, 5, 5, 
/*      'p' */ 5, 5, 5, 5, 5, 22, 5, 5, 20, 5, 5, 10, 39, 11 };

    static sbyte MapC(int code)
    { // '\0' <= code <= '\U0010FFFF'
      if (code < 126) // '\0' <= code <= '}'
        return mapC0[code - 0];
      else // '~' <= code <= '\U0010FFFF'
        return (sbyte)24;
    }
#endregion

    static Table[] NxS = new Table[201] {
/* NxS[   0] */ new Table(0, 0, 0, null), // Shortest string ""
/* NxS[   1] */ new Table(0, 0, -1, null), // Shortest string ""
/* NxS[   2] */ // Shortest string "^/"
      new Table(1, 9, -1, new short[] {14, -1, -1, -1, -1, -1, 
          -1, -1, 15}),
/* NxS[   3] */ new Table(0, 0, -1, null), // Shortest string "["
/* NxS[   4] */ // Shortest string "\r"
      new Table(0, 1, -1, new short[] {1}),
/* NxS[   5] */ // Shortest string "^G"
      new Table(19, 28, -1, new short[] {5, 5, 5, 5, 5, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 5, 5, 5, -1, -1, 
          -1, -1, -1, -1, 5, 5}),
/* NxS[   6] */ // Shortest string "^%"
      new Table(7, 5, -1, new short[] {9, -1, -1, 10, 11}),
/* NxS[   7] */ // Shortest string "^@"
      new Table(20, 26, -1, new short[] {8, 8, 8, 8, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 8, 8, 8, -1, -1, -1, 
          -1, -1, -1, 8}),
/* NxS[   8] */ // Shortest string "^@G"
      new Table(19, 28, -1, new short[] {8, 8, 8, 8, 8, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 8, 8, 8, -1, -1, 
          -1, -1, -1, -1, 8, 8}),
/* NxS[   9] */ new Table(0, 0, -1, null), // Shortest string "^%%"
/* NxS[  10] */ new Table(0, 0, -1, null), // Shortest string "^%{"
/* NxS[  11] */ new Table(0, 0, -1, null), // Shortest string "^%}"
/* NxS[  12] */ new Table(0, 0, -1, null), // Shortest string "^\t/"
/* NxS[  13] */ // Shortest string "^\t%"
      new Table(7, 1, -1, new short[] {9}),
/* NxS[  14] */ // Shortest string "//"
      new Table(0, 5, 14, new short[] {-1, 14, 14, 14, -1}),
/* NxS[  15] */ // Shortest string "^/*"
      new Table(0, 10, 15, new short[] {-1, 15, 15, 15, -1, 15, 
          15, 15, 15, 16}),
/* NxS[  16] */ // Shortest string "^/**"
      new Table(1, 9, -1, new short[] {17, -1, -1, -1, -1, -1, 
          -1, -1, 16}),
/* NxS[  17] */ new Table(0, 0, -1, null), // Shortest string "^/**/"
/* NxS[  18] */ // Shortest string "/"
      new Table(1, 1, -1, new short[] {14}),
/* NxS[  19] */ // Shortest string "/"
      new Table(0, 5, 20, new short[] {-1, 14, 20, 20, -1}),
/* NxS[  20] */ // Shortest string "["
      new Table(0, 5, 20, new short[] {-1, 20, 20, 20, -1}),
/* NxS[  21] */ // Shortest string "^/"
      new Table(1, 9, -1, new short[] {14, -1, -1, -1, -1, -1, 
          -1, -1, 26}),
/* NxS[  22] */ new Table(0, 0, -1, null), // Shortest string "^["
/* NxS[  23] */ // Shortest string "^%"
      new Table(7, 5, -1, new short[] {9, -1, -1, 10, 11}),
/* NxS[  24] */ // Shortest string "^<"
      new Table(30, 1, -1, new short[] {140}),
/* NxS[  25] */ new Table(0, 0, -1, null), // Shortest string "^<<EOF>>"
/* NxS[  26] */ // Shortest string "/*"
      new Table(0, 10, 26, new short[] {-1, 26, 26, 26, -1, 26, 
          26, 26, 26, 27}),
/* NxS[  27] */ // Shortest string "/**"
      new Table(1, 9, -1, new short[] {28, -1, -1, -1, -1, -1, 
          -1, -1, 27}),
/* NxS[  28] */ new Table(0, 0, -1, null), // Shortest string "/**/"
/* NxS[  29] */ // Shortest string "/"
      new Table(1, 9, -1, new short[] {14, -1, -1, -1, -1, -1, 
          -1, -1, 26}),
/* NxS[  30] */ // Shortest string "/"
      new Table(28, 22, -1, new short[] {44, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, 14, -1, -1, -1, -1, -1, -1, -1, 26}),
/* NxS[  31] */ new Table(0, 0, -1, null), // Shortest string "["
/* NxS[  32] */ // Shortest string "G"
      new Table(19, 28, -1, new short[] {32, 32, 32, 32, 32, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 32, 32, 32, -1, -1, 
          -1, -1, -1, -1, 32, 32}),
/* NxS[  33] */ // Shortest string "8"
      new Table(6, 14, -1, new short[] {33, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, 33}),
/* NxS[  34] */ // Shortest string "^%"
      new Table(7, 22, -1, new short[] {9, -1, -1, -1, 57, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 44}),
/* NxS[  35] */ // Shortest string "@"
      new Table(16, 1, -1, new short[] {164}),
/* NxS[  36] */ new Table(0, 0, -1, null), // Shortest string "{"
/* NxS[  37] */ new Table(0, 0, -1, null), // Shortest string "}"
/* NxS[  38] */ new Table(0, 0, -1, null), // Shortest string ","
/* NxS[  39] */ // Shortest string ">"
      new Table(13, 16, -1, new short[] {44, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, 44}),
/* NxS[  40] */ // Shortest string "\""
      new Table(0, 17, 162, new short[] {53, 162, 162, -1, 54, 162, 
          162, 162, 162, 162, 162, 162, 162, 162, -1, 163, 55}),
/* NxS[  41] */ new Table(0, 0, -1, null), // Shortest string "]"
/* NxS[  42] */ // Shortest string "-"
      new Table(25, 4, -1, new short[] {44, -1, -1, 44}),
/* NxS[  43] */ // Shortest string "+"
      new Table(26, 3, -1, new short[] {44, -1, 44}),
/* NxS[  44] */ new Table(0, 0, -1, null), // Shortest string "#"
/* NxS[  45] */ // Shortest string "%"
      new Table(28, 1, -1, new short[] {44}),
/* NxS[  46] */ // Shortest string "<"
      new Table(28, 3, -1, new short[] {44, -1, 44}),
/* NxS[  47] */ // Shortest string "'"
      new Table(31, 25, 148, new short[] {-1, 148, 148, 148, 148, 148, 
          148, 148, 148, -1, 148, 148, -1, -1, 148, 148, 148, 148, 148, 148, 148, 148, 
          148, -1, 149}),
/* NxS[  48] */ new Table(0, 0, -1, null), // Shortest string ";"
/* NxS[  49] */ new Table(0, 0, -1, null), // Shortest string "."
/* NxS[  50] */ new Table(0, 0, -1, null), // Shortest string "("
/* NxS[  51] */ new Table(0, 0, -1, null), // Shortest string ")"
/* NxS[  52] */ new Table(0, 0, -1, null), // Shortest string "'/'"
/* NxS[  53] */ new Table(0, 0, -1, null), // Shortest string ""
/* NxS[  54] */ // Shortest string "\"\r"
      new Table(0, 1, -1, new short[] {53}),
/* NxS[  55] */ new Table(0, 0, -1, null), // Shortest string "\"\""
/* NxS[  56] */ // Shortest string "@\"\""
      new Table(16, 1, -1, new short[] {164}),
/* NxS[  57] */ new Table(0, 0, -1, null), // Shortest string "^%}"
/* NxS[  58] */ // Shortest string "^%"
      new Table(28, 20, -1, new short[] {44, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 9}),
/* NxS[  59] */ new Table(0, 0, -1, null), // Shortest string "{"
/* NxS[  60] */ new Table(0, 0, -1, null), // Shortest string "}"
/* NxS[  61] */ new Table(0, 0, -1, null), // Shortest string ""
/* NxS[  62] */ // Shortest string "\r"
      new Table(0, 1, -1, new short[] {61}),
/* NxS[  63] */ // Shortest string "^/"
      new Table(0, 5, 64, new short[] {-1, 14, 64, 64, -1}),
/* NxS[  64] */ // Shortest string "^["
      new Table(0, 5, 64, new short[] {-1, 64, 64, 64, -1}),
/* NxS[  65] */ // Shortest string "^@"
      new Table(0, 17, 64, new short[] {-1, 64, 64, 64, -1, 64, 
          64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 68}),
/* NxS[  66] */ // Shortest string "^\""
      new Table(0, 17, 66, new short[] {53, 66, 66, 64, 54, 66, 
          66, 66, 66, 66, 66, 66, 66, 66, 64, 67, 64}),
/* NxS[  67] */ // Shortest string "^\"\\"
      new Table(0, 5, 66, new short[] {-1, 66, 66, 66, -1}),
/* NxS[  68] */ // Shortest string "^@\""
      new Table(0, 17, 68, new short[] {164, 68, 68, 68, 164, 68, 
          68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 65}),
/* NxS[  69] */ // Shortest string ""
      new Table(0, 10, 72, new short[] {1, 71, 72, 72, 4, 72, 
          72, 72, 72, 75}),
/* NxS[  70] */ // Shortest string "^"
      new Table(0, 18, 72, new short[] {1, 71, 72, 73, 4, 72, 
          72, 74, 72, 75, 72, 72, 72, 72, 72, 72, 72, 73}),
/* NxS[  71] */ // Shortest string "/"
      new Table(0, 10, 72, new short[] {-1, 14, 72, 72, -1, 72, 
          72, 72, 72, 75}),
/* NxS[  72] */ // Shortest string "["
      new Table(0, 10, 72, new short[] {-1, 72, 72, 72, -1, 72, 
          72, 72, 72, 75}),
/* NxS[  73] */ // Shortest string "^\t"
      new Table(0, 18, 72, new short[] {-1, 72, 72, 73, -1, 72, 
          72, 74, 72, 75, 72, 72, 72, 72, 72, 72, 72, 73}),
/* NxS[  74] */ // Shortest string "^%"
      new Table(0, 10, 72, new short[] {-1, 72, 72, 72, -1, 72, 
          72, 77, 72, 75}),
/* NxS[  75] */ // Shortest string "*"
      new Table(1, 9, -1, new short[] {76, -1, -1, -1, -1, -1, 
          -1, -1, 75}),
/* NxS[  76] */ new Table(0, 0, -1, null), // Shortest string "*/"
/* NxS[  77] */ // Shortest string "^%%"
      new Table(0, 10, 72, new short[] {-1, 72, 72, 72, -1, 72, 
          72, 72, 72, 75}),
/* NxS[  78] */ new Table(0, 0, -1, null), // Shortest string ""
/* NxS[  79] */ // Shortest string "/"
      new Table(1, 1, -1, new short[] {14}),
/* NxS[  80] */ new Table(0, 0, -1, null), // Shortest string "["
/* NxS[  81] */ // Shortest string "\r"
      new Table(0, 1, -1, new short[] {78}),
/* NxS[  82] */ // Shortest string "^%"
      new Table(7, 1, -1, new short[] {9}),
/* NxS[  83] */ new Table(0, 0, -1, null), // Shortest string "{"
/* NxS[  84] */ new Table(0, 0, -1, null), // Shortest string "|"
/* NxS[  85] */ // Shortest string "/"
      new Table(0, 5, 86, new short[] {-1, 14, 86, 86, -1}),
/* NxS[  86] */ // Shortest string "["
      new Table(0, 5, 86, new short[] {-1, 86, 86, 86, -1}),
/* NxS[  87] */ // Shortest string "/"
      new Table(0, 18, 89, new short[] {-1, 97, 178, -1, -1, 89, 
          89, 89, 89, 89, 179, 89, 89, 89, 89, 180, 177, -1}),
/* NxS[  88] */ // Shortest string "["
      new Table(0, 19, 186, new short[] {-1, 186, 186, 186, -1, 186, 
          186, 186, 186, 186, 186, 186, 186, 186, 186, 187, 186, 186, -1}),
/* NxS[  89] */ // Shortest string "G"
      new Table(0, 18, 89, new short[] {-1, 89, 178, -1, -1, 89, 
          89, 89, 89, 89, 179, 89, 89, 89, 89, 180, 177, -1}),
/* NxS[  90] */ // Shortest string "^%"
      new Table(0, 18, 89, new short[] {-1, 89, 178, -1, -1, 89, 
          89, 96, 89, 89, 179, 89, 89, 89, 89, 180, 177, -1}),
/* NxS[  91] */ // Shortest string "{"
      new Table(19, 31, -1, new short[] {183, 182, 182, 182, 182, -1, 
          184, 184, -1, -1, -1, -1, -1, -1, -1, -1, -1, 182, 182, 182, -1, -1, 
          -1, -1, -1, -1, 182, 183, -1, -1, 184}),
/* NxS[  92] */ // Shortest string "\\"
      new Table(0, 5, 89, new short[] {-1, 89, 89, 89, -1}),
/* NxS[  93] */ // Shortest string "\""
      new Table(0, 17, 177, new short[] {94, 177, 177, -1, 95, 177, 
          177, 177, 177, 177, 177, 177, 177, 177, -1, 181, 89}),
/* NxS[  94] */ new Table(0, 0, -1, null), // Shortest string ""
/* NxS[  95] */ // Shortest string "\"\r"
      new Table(0, 1, -1, new short[] {94}),
/* NxS[  96] */ // Shortest string "^%%"
      new Table(0, 18, 89, new short[] {-1, 89, 178, -1, -1, 89, 
          89, 89, 89, 89, 179, 89, 89, 89, 89, 180, 177, -1}),
/* NxS[  97] */ // Shortest string "//"
      new Table(0, 18, 97, new short[] {-1, 97, 98, 14, -1, 97, 
          97, 97, 97, 97, 99, 97, 97, 97, 97, 100, 101, 14}),
/* NxS[  98] */ // Shortest string "//["
      new Table(0, 19, 107, new short[] {-1, 107, 107, 107, -1, 107, 
          107, 107, 107, 107, 107, 107, 107, 107, 107, 108, 107, 107, 14}),
/* NxS[  99] */ // Shortest string "//{"
      new Table(19, 31, 14, new short[] {104, 103, 103, 103, 103, 14, 
          105, 105, 14, 14, 14, 14, 14, 14, 14, 14, 14, 103, 103, 103, 14, -1, 
          14, 14, 14, -1, 103, 104, 14, 14, 105}),
/* NxS[ 100] */ // Shortest string "//\\"
      new Table(0, 5, 97, new short[] {-1, 97, 97, 97, -1}),
/* NxS[ 101] */ // Shortest string "//\""
      new Table(0, 17, 101, new short[] {94, 101, 101, 14, 95, 101, 
          101, 101, 101, 101, 101, 101, 101, 101, 14, 102, 97}),
/* NxS[ 102] */ // Shortest string "//\"\\"
      new Table(0, 5, 101, new short[] {-1, 101, 101, 101, -1}),
/* NxS[ 103] */ // Shortest string "//{G"
      new Table(36, 28, 14, new short[] {103, 103, 103, 14, -1, 14, 
          14, 14, -1, 103, 103, 14, 14, 14, 14, 97, 14, 14, 14, 14, 14, 14, 
          14, 103, 103, 103, 103, 103}),
/* NxS[ 104] */ // Shortest string "//{8"
      new Table(0, 20, 14, new short[] {-1, 14, 14, 14, -1, 14, 
          104, 14, 14, 14, 14, 97, 106, 14, 14, 14, 14, 14, 14, 104}),
/* NxS[ 105] */ // Shortest string "//{*"
      new Table(0, 12, 14, new short[] {-1, 14, 14, 14, -1, 14, 
          14, 14, 14, 14, 14, 97}),
/* NxS[ 106] */ // Shortest string "//{8,"
      new Table(0, 20, 14, new short[] {-1, 14, 14, 14, -1, 14, 
          106, 14, 14, 14, 14, 97, 14, 14, 14, 14, 14, 14, 14, 106}),
/* NxS[ 107] */ // Shortest string "//[/"
      new Table(0, 19, 107, new short[] {-1, 107, 107, 107, -1, 107, 
          107, 107, 107, 107, 107, 107, 107, 107, 107, 108, 107, 107, 97}),
/* NxS[ 108] */ // Shortest string "//[\\"
      new Table(0, 5, 107, new short[] {-1, 107, 107, 107, -1}),
/* NxS[ 109] */ // Shortest string "^\t"
      new Table(3, 15, -1, new short[] {109, -1, -1, -1, 165, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, 109}),
/* NxS[ 110] */ // Shortest string "G"
      new Table(19, 28, -1, new short[] {110, 110, 110, 110, 110, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 110, 110, 110, -1, -1, 
          -1, -1, -1, -1, 110, 110}),
/* NxS[ 111] */ // Shortest string "8"
      new Table(6, 14, -1, new short[] {111, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, 111}),
/* NxS[ 112] */ // Shortest string "^%"
      new Table(7, 1, -1, new short[] {9}),
/* NxS[ 113] */ new Table(0, 0, -1, null), // Shortest string "*"
/* NxS[ 114] */ new Table(0, 0, -1, null), // Shortest string ","
/* NxS[ 115] */ new Table(0, 0, -1, null), // Shortest string ">"
/* NxS[ 116] */ // Shortest string "\t"
      new Table(3, 15, -1, new short[] {116, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, 116}),
/* NxS[ 117] */ new Table(0, 0, -1, null), // Shortest string ""
/* NxS[ 118] */ // Shortest string "/"
      new Table(0, 18, 119, new short[] {-1, 14, 119, -1, -1, 119, 
          119, 119, 119, 119, 119, 119, 119, 119, 119, 119, 119, -1}),
/* NxS[ 119] */ // Shortest string "["
      new Table(0, 18, 119, new short[] {-1, 119, 119, -1, -1, 119, 
          119, 119, 119, 119, 119, 119, 119, 119, 119, 119, 119, -1}),
/* NxS[ 120] */ // Shortest string "^\t"
      new Table(3, 15, -1, new short[] {120, -1, -1, -1, 165, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, 120}),
/* NxS[ 121] */ // Shortest string "\r"
      new Table(0, 1, -1, new short[] {117}),
/* NxS[ 122] */ // Shortest string "\t"
      new Table(3, 15, -1, new short[] {122, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, 122}),
/* NxS[ 123] */ // Shortest string "/"
      new Table(0, 5, 124, new short[] {-1, 14, 124, 124, -1}),
/* NxS[ 124] */ // Shortest string "["
      new Table(0, 5, 124, new short[] {-1, 124, 124, 124, -1}),
/* NxS[ 125] */ // Shortest string "\t"
      new Table(0, 18, 124, new short[] {-1, 124, 124, 125, -1, 124, 
          124, 124, 124, 124, 124, 124, 124, 124, 124, 124, 124, 125}),
/* NxS[ 126] */ // Shortest string "/"
      new Table(1, 9, -1, new short[] {14, -1, -1, -1, -1, -1, 
          -1, -1, 26}),
/* NxS[ 127] */ new Table(0, 0, -1, null), // Shortest string "["
/* NxS[ 128] */ // Shortest string "^\t"
      new Table(3, 15, -1, new short[] {128, -1, -1, -1, 165, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, 128}),
/* NxS[ 129] */ // Shortest string "^%"
      new Table(7, 1, -1, new short[] {9}),
/* NxS[ 130] */ new Table(0, 0, -1, null), // Shortest string "}"
/* NxS[ 131] */ // Shortest string "<"
      new Table(30, 1, -1, new short[] {196}),
/* NxS[ 132] */ new Table(0, 0, -1, null), // Shortest string "<<EOF>>"
/* NxS[ 133] */ // Shortest string ""
      new Table(0, 18, 3, new short[] {1, 18, 3, -1, 4, 3, 
          3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, -1}),
/* NxS[ 134] */ // Shortest string "^"
      new Table(36, 28, 3, new short[] {5, 5, 5, 3, 1, 2, 
          3, 135, 4, 5, 3, 6, 7, 3, 3, 3, 3, 3, 3, 3, 3, 135, 
          3, 3, 5, 5, 5, 5}),
/* NxS[ 135] */ // Shortest string "^\t"
      new Table(0, 18, 12, new short[] {-1, 12, 12, 135, -1, 12, 
          12, 13, 12, 12, 12, 12, 12, 12, 12, 12, 12, 135}),
/* NxS[ 136] */ // Shortest string ""
      new Table(0, 5, 20, new short[] {1, 19, 20, 20, 4}),
/* NxS[ 137] */ // Shortest string "^"
      new Table(0, 5, 20, new short[] {1, 19, 20, 20, 4}),
/* NxS[ 138] */ // Shortest string ""
      new Table(0, 18, 3, new short[] {1, 29, 3, -1, 4, 3, 
          3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, -1}),
/* NxS[ 139] */ // Shortest string "^"
      new Table(30, 28, 22, new short[] {24, 22, 22, 22, 22, 22, 
          22, 22, 22, 22, 1, 21, 22, 135, 4, 22, 22, 23, 22, 22, 22, 22, 
          22, 22, 22, 22, 22, 135}),
/* NxS[ 140] */ // Shortest string "^<<"
      new Table(36, 1, -1, new short[] {141}),
/* NxS[ 141] */ // Shortest string "^<<E"
      new Table(37, 1, -1, new short[] {142}),
/* NxS[ 142] */ // Shortest string "^<<EO"
      new Table(38, 1, -1, new short[] {143}),
/* NxS[ 143] */ // Shortest string "^<<EOF"
      new Table(13, 1, -1, new short[] {144}),
/* NxS[ 144] */ // Shortest string "^<<EOF>"
      new Table(13, 1, -1, new short[] {25}),
/* NxS[ 145] */ // Shortest string ""
      new Table(24, 36, 32, new short[] {3, 42, 43, 44, 45, 45, 
          46, 47, 48, 49, 50, 51, 32, 32, 32, 44, 1, 30, 31, -1, 4, 32, 
          33, 45, 35, 45, 36, 37, 38, 39, 3, 3, 40, -1, 41, 33}),
/* NxS[ 146] */ // Shortest string "^"
      new Table(24, 36, 32, new short[] {3, 42, 43, 44, 45, 45, 
          46, 47, 48, 49, 50, 51, 32, 32, 32, 44, 1, 30, 31, 147, 4, 32, 
          33, 34, 35, 45, 36, 37, 38, 39, 3, 3, 40, 147, 41, 33}),
/* NxS[ 147] */ // Shortest string "^\t"
      new Table(3, 15, -1, new short[] {147, -1, -1, -1, 165, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, 147}),
/* NxS[ 148] */ // Shortest string "'/"
      new Table(31, 1, -1, new short[] {52}),
/* NxS[ 149] */ // Shortest string "'\\"
      new Table(0, 24, 148, new short[] {-1, 148, 148, 148, -1, 148, 
          148, 148, 148, 148, 148, 148, 148, 148, 148, 148, 148, 148, 148, 150, 151, 148, 
          152, 153}),
/* NxS[ 150] */ // Shortest string "'\\0"
      new Table(19, 13, -1, new short[] {161, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, 52}),
/* NxS[ 151] */ // Shortest string "'\\x"
      new Table(19, 28, -1, new short[] {160, -1, 160, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, 52, -1, -1, -1, -1, 160, -1, 160, -1, -1, 
          -1, -1, -1, -1, -1, 160}),
/* NxS[ 152] */ // Shortest string "'\\u"
      new Table(19, 28, -1, new short[] {158, -1, 158, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, 52, -1, -1, -1, -1, 158, -1, 158, -1, -1, 
          -1, -1, -1, -1, -1, 158}),
/* NxS[ 153] */ // Shortest string "'\\U"
      new Table(19, 28, -1, new short[] {154, -1, 154, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, 52, -1, -1, -1, -1, 154, -1, 154, -1, -1, 
          -1, -1, -1, -1, -1, 154}),
/* NxS[ 154] */ // Shortest string "'\\U8"
      new Table(36, 26, -1, new short[] {155, -1, 155, -1, -1, -1, 
          -1, -1, -1, -1, 155, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, 155, -1, 155}),
/* NxS[ 155] */ // Shortest string "'\\U88"
      new Table(36, 26, -1, new short[] {156, -1, 156, -1, -1, -1, 
          -1, -1, -1, -1, 156, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, 156, -1, 156}),
/* NxS[ 156] */ // Shortest string "'\\U888"
      new Table(36, 26, -1, new short[] {157, -1, 157, -1, -1, -1, 
          -1, -1, -1, -1, 157, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, 157, -1, 157}),
/* NxS[ 157] */ // Shortest string "'\\U8888"
      new Table(36, 26, -1, new short[] {158, -1, 158, -1, -1, -1, 
          -1, -1, -1, -1, 158, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, 158, -1, 158}),
/* NxS[ 158] */ // Shortest string "'\\u8"
      new Table(36, 26, -1, new short[] {159, -1, 159, -1, -1, -1, 
          -1, -1, -1, -1, 159, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, 159, -1, 159}),
/* NxS[ 159] */ // Shortest string "'\\u88"
      new Table(36, 26, -1, new short[] {160, -1, 160, -1, -1, -1, 
          -1, -1, -1, -1, 160, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, 160, -1, 160}),
/* NxS[ 160] */ // Shortest string "'\\x8"
      new Table(36, 26, -1, new short[] {148, -1, 148, -1, -1, -1, 
          -1, -1, -1, -1, 148, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, 148, -1, 148}),
/* NxS[ 161] */ // Shortest string "'\\00"
      new Table(19, 1, -1, new short[] {148}),
/* NxS[ 162] */ // Shortest string "\"/"
      new Table(0, 17, 162, new short[] {53, 162, 162, -1, 54, 162, 
          162, 162, 162, 162, 162, 162, 162, 162, -1, 163, 55}),
/* NxS[ 163] */ // Shortest string "\"\\"
      new Table(0, 5, 162, new short[] {-1, 162, 162, 162, -1}),
/* NxS[ 164] */ // Shortest string "@\""
      new Table(16, 1, 164, new short[] {56}),
/* NxS[ 165] */ // Shortest string "^\t%"
      new Table(7, 1, -1, new short[] {9}),
/* NxS[ 166] */ // Shortest string ""
      new Table(24, 36, 32, new short[] {3, 42, 43, 44, 45, 45, 
          46, 47, 48, 49, 50, 51, 32, 32, 32, 44, 1, 30, 31, -1, 4, 32, 
          33, 45, 35, 45, 59, 60, 38, 39, 3, 3, 40, -1, 41, 33}),
/* NxS[ 167] */ // Shortest string "^"
      new Table(24, 36, 32, new short[] {3, 42, 43, 44, 45, 45, 
          46, 47, 48, 49, 50, 51, 32, 32, 32, 44, 1, 30, 31, 147, 4, 32, 
          33, 58, 35, 45, 59, 60, 38, 39, 3, 3, 40, 147, 41, 33}),
/* NxS[ 168] */ // Shortest string ""
      new Table(24, 36, 32, new short[] {3, 42, 43, 44, 45, 45, 
          46, 47, 48, 49, 50, 51, 32, 32, 32, 44, 61, 30, 31, -1, 62, 32, 
          33, 45, 35, 45, 36, 37, 38, 39, 3, 3, 40, -1, 41, 33}),
/* NxS[ 169] */ // Shortest string "^"
      new Table(24, 36, 32, new short[] {3, 42, 43, 44, 45, 45, 
          46, 47, 48, 49, 50, 51, 32, 32, 32, 44, 61, 30, 31, 147, 62, 32, 
          33, 58, 35, 45, 36, 37, 38, 39, 3, 3, 40, 147, 41, 33}),
/* NxS[ 170] */ // Shortest string "^"
      new Table(0, 18, 64, new short[] {1, 63, 64, 147, 4, 64, 
          64, 64, 65, 64, 64, 64, 64, 64, 64, 64, 66, 147}),
/* NxS[ 171] */ // Shortest string ""
      new Table(39, 19, 80, new short[] {84, 78, 79, 80, -1, 81, 
          80, 80, 80, 80, 80, 83, 80, 80, 80, 80, 80, 80, -1}),
/* NxS[ 172] */ // Shortest string "^"
      new Table(39, 19, 80, new short[] {84, 78, 79, 80, 147, 81, 
          80, 80, 82, 80, 80, 83, 80, 80, 80, 80, 80, 80, 147}),
/* NxS[ 173] */ // Shortest string ""
      new Table(0, 18, 86, new short[] {61, 85, 86, -1, 62, 86, 
          86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, -1}),
/* NxS[ 174] */ // Shortest string "^"
      new Table(0, 18, 86, new short[] {61, 85, 86, 147, 62, 86, 
          86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 86, 147}),
/* NxS[ 175] */ // Shortest string ""
      new Table(0, 18, 89, new short[] {1, 87, 88, -1, 4, 89, 
          89, 89, 89, 89, 91, 89, 89, 89, 89, 92, 93, -1}),
/* NxS[ 176] */ // Shortest string "^"
      new Table(0, 18, 89, new short[] {1, 87, 88, 147, 4, 89, 
          89, 90, 89, 89, 91, 89, 89, 89, 89, 92, 93, 147}),
/* NxS[ 177] */ // Shortest string "/\""
      new Table(0, 17, 177, new short[] {94, 177, 177, -1, 95, 177, 
          177, 177, 177, 177, 177, 177, 177, 177, -1, 181, 89}),
/* NxS[ 178] */ // Shortest string "/["
      new Table(0, 19, 186, new short[] {-1, 186, 186, 186, -1, 186, 
          186, 186, 186, 186, 186, 186, 186, 186, 186, 187, 186, 186, -1}),
/* NxS[ 179] */ // Shortest string "/{"
      new Table(19, 31, -1, new short[] {183, 182, 182, 182, 182, -1, 
          184, 184, -1, -1, -1, -1, -1, -1, -1, -1, -1, 182, 182, 182, -1, -1, 
          -1, -1, -1, -1, 182, 183, -1, -1, 184}),
/* NxS[ 180] */ // Shortest string "/\\"
      new Table(0, 5, 89, new short[] {-1, 89, 89, 89, -1}),
/* NxS[ 181] */ // Shortest string "\"\\"
      new Table(0, 5, 177, new short[] {-1, 177, 177, 177, -1}),
/* NxS[ 182] */ // Shortest string "{G"
      new Table(36, 28, -1, new short[] {182, 182, 182, -1, -1, -1, 
          -1, -1, -1, 182, 182, -1, -1, -1, -1, 89, -1, -1, -1, -1, -1, -1, 
          -1, 182, 182, 182, 182, 182}),
/* NxS[ 183] */ // Shortest string "{8"
      new Table(6, 14, -1, new short[] {183, -1, -1, -1, -1, 89, 
          185, -1, -1, -1, -1, -1, -1, 183}),
/* NxS[ 184] */ // Shortest string "{*"
      new Table(11, 1, -1, new short[] {89}),
/* NxS[ 185] */ // Shortest string "{8,"
      new Table(6, 14, -1, new short[] {185, -1, -1, -1, -1, 89, 
          -1, -1, -1, -1, -1, -1, -1, 185}),
/* NxS[ 186] */ // Shortest string "[/"
      new Table(0, 19, 186, new short[] {-1, 186, 186, 186, -1, 186, 
          186, 186, 186, 186, 186, 186, 186, 186, 186, 187, 186, 186, 89}),
/* NxS[ 187] */ // Shortest string "[\\"
      new Table(0, 5, 186, new short[] {-1, 186, 186, 186, -1}),
/* NxS[ 188] */ // Shortest string ""
      new Table(36, 28, 3, new short[] {110, 110, 110, 3, 61, 18, 
          3, 116, 62, 110, 111, 3, 3, 113, 3, 3, 114, 115, 3, 3, 3, 116, 
          3, 111, 110, 110, 110, 110}),
/* NxS[ 189] */ // Shortest string "^"
      new Table(36, 28, 3, new short[] {110, 110, 110, 3, 61, 18, 
          3, 109, 62, 110, 111, 112, 3, 113, 3, 3, 114, 115, 3, 3, 3, 109, 
          3, 111, 110, 110, 110, 110}),
/* NxS[ 190] */ // Shortest string ""
      new Table(0, 18, 119, new short[] {117, 118, 119, 122, 121, 119, 
          119, 119, 119, 119, 119, 119, 119, 119, 119, 119, 119, 122}),
/* NxS[ 191] */ // Shortest string "^"
      new Table(0, 18, 119, new short[] {117, 118, 119, 120, 121, 119, 
          119, 119, 119, 119, 119, 119, 119, 119, 119, 119, 119, 120}),
/* NxS[ 192] */ // Shortest string ""
      new Table(0, 18, 124, new short[] {61, 123, 124, 125, 62, 124, 
          124, 124, 124, 124, 124, 124, 124, 124, 124, 124, 124, 125}),
/* NxS[ 193] */ // Shortest string "^"
      new Table(0, 18, 124, new short[] {61, 123, 124, 125, 62, 124, 
          124, 124, 124, 124, 124, 124, 124, 124, 124, 124, 124, 125}),
/* NxS[ 194] */ // Shortest string ""
      new Table(30, 28, 127, new short[] {131, 127, 127, 127, 127, 127, 
          127, 127, 127, 127, 1, 126, 127, -1, 4, 127, 127, 127, 127, 127, 127, 130, 
          127, 127, 127, 127, 127, -1}),
/* NxS[ 195] */ // Shortest string "^"
      new Table(30, 28, 127, new short[] {131, 127, 127, 127, 127, 127, 
          127, 127, 127, 127, 1, 126, 127, 128, 4, 127, 127, 129, 127, 127, 127, 130, 
          127, 127, 127, 127, 127, 128}),
/* NxS[ 196] */ // Shortest string "<<"
      new Table(36, 1, -1, new short[] {197}),
/* NxS[ 197] */ // Shortest string "<<E"
      new Table(37, 1, -1, new short[] {198}),
/* NxS[ 198] */ // Shortest string "<<EO"
      new Table(38, 1, -1, new short[] {199}),
/* NxS[ 199] */ // Shortest string "<<EOF"
      new Table(13, 1, -1, new short[] {200}),
/* NxS[ 200] */ // Shortest string "<<EOF>"
      new Table(13, 1, -1, new short[] {132}),
    };

int NextState() {
    if (code == ScanBuff.EndOfFile)
        return eofNum;
    else
        unchecked {
            int rslt;
            int idx = MapC(code) - NxS[state].min;
            if (idx < 0) idx += 40;
            if ((uint)idx >= (uint)NxS[state].rng) rslt = NxS[state].dflt;
            else rslt = NxS[state].nxt[idx];
            return rslt;
        }
}

#endregion


#if BACKUP
        // ==============================================================
        // == Nested struct used for backup in automata that do backup ==
        // ==============================================================

        struct Context // class used for automaton backup.
        {
            public int bPos;
            public int rPos; // scanner.readPos saved value
            public int cCol;
            public int lNum; // Need this in case of backup over EOL.
            public int state;
            public int cChr;
        }
        
        private Context ctx = new Context();
#endif // BACKUP

        // ==============================================================
        // ==== Nested struct to support input switching in scanners ====
        // ==============================================================

		struct BufferContext {
            internal ScanBuff buffSv;
			internal int chrSv;
			internal int cColSv;
			internal int lNumSv;
		}

        // ==============================================================
        // ===== Private methods to save and restore buffer contexts ====
        // ==============================================================

        /// <summary>
        /// This method creates a buffer context record from
        /// the current buffer object, together with some
        /// scanner state values. 
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        BufferContext MkBuffCtx()
		{
			BufferContext rslt;
			rslt.buffSv = this.buffer;
			rslt.chrSv = this.code;
			rslt.cColSv = this.cCol;
			rslt.lNumSv = this.lNum;
			return rslt;
		}

        /// <summary>
        /// This method restores the buffer value and allied
        /// scanner state from the given context record value.
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        void RestoreBuffCtx(BufferContext value)
		{
			this.buffer = value.buffSv;
			this.code = value.chrSv;
			this.cCol = value.cColSv;
			this.lNum = value.lNumSv;
        } 
        // =================== End Nested classes =======================

#if !NOFILES
     internal Scanner(Stream file) {
            SetSource(file, -1); // unicode option
        }

        public Scanner(Stream file, string codepage) {
            SetSource(file, CodePageHandling.GetCodePage(codepage));
        }   
#endif // !NOFILES

     internal Scanner() { }

        private int readPos;

        void GetCode()
        {
            if (code == '\n')  // This needs to be fixed for other conventions
                               // i.e. [\r\n\205\u2028\u2029]
            { 
                cCol = -1;
                lNum++;
            }
            readPos = buffer.Pos;

            // Now read new codepoint.
            code = buffer.Read();
            if (code > ScanBuff.EndOfFile)
            {
#if (!BYTEMODE)
                if (code >= 0xD800 && code <= 0xDBFF)
                {
                    int next = buffer.Read();
                    if (next < 0xDC00 || next > 0xDFFF)
                        code = ScanBuff.UnicodeReplacementChar;
                    else
                        code = (0x10000 + ((code & 0x3FF) << 10) + (next & 0x3FF));
                }
#endif
                cCol++;
            }
        }

        void MarkToken()
        {
#if (!PERSIST)
            buffer.Mark();
#endif
            tokPos = readPos;
            tokLin = lNum;
            tokCol = cCol;
        }
        
        void MarkEnd()
        {
            tokTxt = null;
            tokEPos = readPos;
            tokELin = lNum;
            tokECol = cCol;
        }

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int Peek()
        {
            int rslt, codeSv = code, cColSv = cCol, lNumSv = lNum, bPosSv = buffer.Pos;
            GetCode(); rslt = code;
            lNum = lNumSv; cCol = cColSv; code = codeSv; buffer.Pos = bPosSv;
            return rslt;
        }

        // ==============================================================
        // =====    Initialization of string-based input buffers     ====
        // ==============================================================

        /// <summary>
        /// Create and initialize a StringBuff buffer object for this scanner
        /// </summary>
        /// <param name="source">the input string</param>
        /// <param name="offset">starting offset in the string</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(string source, int offset)
        {
            this.buffer = ScanBuff.GetBuffer(source);
            this.buffer.Pos = offset;
            this.lNum = 0;
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            GetCode();
        }

        // ================ LineBuffer Initialization ===================
        /// <summary>
        /// Create and initialize a LineBuff buffer object for this scanner
        /// </summary>
        /// <param name="source">the list of input strings</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(IList<string> source)
        {
            this.buffer = ScanBuff.GetBuffer(source);
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            this.lNum = 0;
            GetCode();
        }

#if !NOFILES        
        // =============== StreamBuffer Initialization ==================

        /// <summary>
        /// Create and initialize a StreamBuff buffer object for this scanner.
        /// StreamBuff is buffer for 8-bit byte files.
        /// </summary>
        /// <param name="source">the input byte stream</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(Stream source)
        {
            this.buffer = ScanBuff.GetBuffer(source);
            this.lNum = 0;
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            GetCode();
        }
        
#if !BYTEMODE
        // ================ TextBuffer Initialization ===================

        /// <summary>
        /// Create and initialize a TextBuff buffer object for this scanner.
        /// TextBuff is a buffer for encoded unicode files.
        /// </summary>
        /// <param name="source">the input text file</param>
        /// <param name="fallbackCodePage">Code page to use if file has
        /// no BOM. For 0, use machine default; for -1, 8-bit binary</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(Stream source, int fallbackCodePage)
        {
            this.buffer = ScanBuff.GetBuffer(source, fallbackCodePage);
            this.lNum = 0;
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            GetCode();
        }
#endif // !BYTEMODE
#endif // !NOFILES
        
        // ==============================================================

#if BABEL
        //
        //  Get the next token for Visual Studio
        //
        //  "state" is the inout mode variable that maintains scanner
        //  state between calls, using the EolState property. In principle,
        //  if the calls of EolState are costly set could be called once
        //  only per line, at the start; and get called only at the end
        //  of the line. This needs more infrastructure ...
        //
        public int GetNext(ref int state, out int start, out int end)
        {
                Tokens next;
            int s, e;
            s = state;        // state at start
            EolState = state;
                next = (Tokens)Scan();
            state = EolState;
            e = state;       // state at end;
            start = tokPos;
            end = tokEPos - 1; // end is the index of last char.
            return (int)next;
        }        
#endif // BABEL

        // ======== AbstractScanner<> Implementation =========

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yylex")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yylex")]
        public override int yylex()
        {
            // parserMax is set by reflecting on the Tokens
            // enumeration.  If maxParseToken is defined
            // that is used, otherwise int.MaxValue is used.
            int next;
            do { next = Scan(); } while (next >= parserMax);
            return next;
        }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int yypos { get { return tokPos; } }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int yyline { get { return tokLin; } }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int yycol { get { return tokCol; } }

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yytext")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yytext")]
        public string yytext
        {
            get 
            {
                if (tokTxt == null) 
                    tokTxt = buffer.GetString(tokPos, tokEPos);
                return tokTxt;
            }
        }

        /// <summary>
        /// Discards all but the first "n" codepoints in the recognized pattern.
        /// Resets the buffer position so that only n codepoints have been consumed;
        /// yytext is also re-evaluated. 
        /// </summary>
        /// <param name="n">The number of codepoints to consume</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        void yyless(int n)
        {
            buffer.Pos = tokPos;
            // Must read at least one char, so set before start.
            cCol = tokCol - 1; 
            GetCode();
            // Now ensure that line counting is correct.
            lNum = tokLin;
            // And count the rest of the text.
            for (int i = 0; i < n; i++) GetCode();
            MarkEnd();
        }
       
        //
        //  It would be nice to count backward in the text
        //  but it does not seem possible to re-establish
        //  the correct column counts except by going forward.
        //
        /// <summary>
        /// Removes the last "n" code points from the pattern.
        /// </summary>
        /// <param name="n">The number to remove</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        void _yytrunc(int n) { yyless(yyleng - n); }
        
        //
        // This is painful, but we no longer count
        // codepoints.  For the overwhelming majority 
        // of cases the single line code is fast, for
        // the others, well, at least it is all in the
        // buffer so no files are touched. Note that we
        // can't use (tokEPos - tokPos) because of the
        // possibility of surrogate pairs in the token.
        //
        /// <summary>
        /// The length of the pattern in codepoints (not the same as 
        /// string-length if the pattern contains any surrogate pairs).
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yyleng")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yyleng")]
        public int yyleng
        {
            get {
                if (tokELin == tokLin)
                    return tokECol - tokCol;
                else
#if BYTEMODE
                    return tokEPos - tokPos;
#else
                {
                    int ch;
                    int count = 0;
                    int save = buffer.Pos;
                    buffer.Pos = tokPos;
                    do {
                        ch = buffer.Read();
                        if (!char.IsHighSurrogate((char)ch)) count++;
                    } while (buffer.Pos < tokEPos && ch != ScanBuff.EndOfFile);
                    buffer.Pos = save;
                    return count;
                }
#endif // BYTEMODE
            }
        }
        
        // ============ methods available in actions ==============

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal int YY_START {
            get { return currentScOrd; }
            set { currentScOrd = value; 
                  currentStart = startState[value]; 
            } 
        }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal void BEGIN(int next) {
            currentScOrd = next;
            currentStart = startState[next];
        }

        // ============== The main tokenizer code =================

        int Scan() {
            try {
                for (; ; ) {
                    int next;              // next state to enter
#if LEFTANCHORS
                    for (;;) {
                        // Discard characters that do not start any pattern.
                        // Must check the left anchor condition after *every* GetCode!
                        state = ((cCol == 0) ? anchorState[currentScOrd] : currentStart);
                        if ((next = NextState()) != goStart) break; // LOOP EXIT HERE...
                        GetCode();
                    }
                    
#else // !LEFTANCHORS
                    state = currentStart;
                    while ((next = NextState()) == goStart) {
                        // At this point, the current character has no
                        // transition from the current state.  We discard 
                        // the "no-match" char.   In traditional LEX such 
                        // characters are echoed to the console.
                        GetCode();
                    }
#endif // LEFTANCHORS                    
                    // At last, a valid transition ...    
                    MarkToken();
                    state = next;
                    GetCode();                    
#if BACKUP
                    bool contextSaved = false;
                    while ((next = NextState()) > eofNum) { // Exit for goStart AND for eofNum
                        if (state <= maxAccept && next > maxAccept) { // need to prepare backup data
                            // Store data for the *latest* accept state that was found.
                            SaveStateAndPos( ref ctx );
                            contextSaved = true;
                        }
                        state = next;
                        GetCode();
                    }
                    if (state > maxAccept && contextSaved)
                        RestoreStateAndPos( ref ctx );
#else  // BACKUP
                    while ((next = NextState()) > eofNum) { // Exit for goStart AND for eofNum
                         state = next;
                         GetCode();
                    }
#endif // BACKUP
                    if (state <= maxAccept) {
                        MarkEnd();
#region ActionSwitch
#pragma warning disable 162, 1522
    switch (state)
    {
        case eofNum:
            switch (currentStart) {
                case 69:
Error(60, comStart);
                    break;
            }
            if (yywrap())
                return (int)Tokens.EOF;
            break;
        case 1: // Recognized '{Eol}',	Shortest string ""
        case 4: // Recognized '{Eol}',	Shortest string "\r"
ResetBadCount(); return (int)Tokens.EOL;
            break;
        case 2: // Recognized '{NotWh}',	Shortest string "^/"
        case 3: // Recognized '{NotWh}',	Shortest string "["
        case 6: // Recognized '{NotWh}',	Shortest string "^%"
        case 7: // Recognized '{NotWh}',	Shortest string "^@"
        case 18: // Recognized '{NotWh}',	Shortest string "/"
        case 29: // In <RULES> Recognized '{NotWh}',	Shortest string "/"
        case 40: // In <UCODE> Recognized '{NotWh}',	Shortest string "\""
        case 47: // In <UCODE> Recognized '{NotWh}',	Shortest string "'"
        case 88: // In <REGEX> Recognized '{NotWh}',	Shortest string "["
        case 92: // In <REGEX> Recognized '{NotWh}',	Shortest string "\\"
        case 93: // In <REGEX> Recognized '{NotWh}',	Shortest string "\""
        case 112: // In <NMLST> Recognized '{NotWh}',	Shortest string "^%"
Error79(TokenSpan()); return (int)Tokens.repErr;
            break;
        case 5: // Recognized '^{Ident}',	Shortest string "^G"
yy_push_state(REGEX); 
                         yy_push_state(SPACE); 
                         return (int)Tokens.name;
            break;
        case 8: // Recognized '^@{Ident}',	Shortest string "^@G"
return (int)GetTagToken(yytext);
            break;
        case 9: // Recognized '^{Space}*%%',	Shortest string "^%%"
        case 77: // In <CMMNT> Recognized '^{Space}*%%',	Shortest string "^%%"
        case 96: // In <REGEX> Recognized '^{Space}*%%',	Shortest string "^%%"
if (yytext.Length > 2)
                             Error(90, TokenSpan());
                         while (scStack.Count > 0) 
                             yy_pop_state();
                         if (YY_START == 0)
                             BEGIN(RULES);
                         else
                             BEGIN(UCODE); 
                         yy_push_state(XPEOL); 
                         return (int)Tokens.PCPC;
            break;
        case 10: // Recognized '^%\{',	Shortest string "^%{"
yy_push_state(UCODE); yy_push_state(XPEOL); return (int)Tokens.lPcBrace;
            break;
        case 11: // Recognized '^%\}',	Shortest string "^%}"
return (int)Tokens.rPcBrace; /* error! */
            break;
        case 12: // Recognized '^{Space}+/{NotWh}',	Shortest string "^\t/"
        case 13: // Recognized '^{Space}+/{NotWh}',	Shortest string "^\t%"
_yytrunc(1); 
yy_push_state(INDNT); return (int)Tokens.lxIndent;
            break;
        case 14: // Recognized '{OneLineCmnt}',	Shortest string "//"
        case 97: // In <REGEX> Recognized '{OneLineCmnt}',	Shortest string "//"
        case 98: // In <REGEX> Recognized '{OneLineCmnt}',	Shortest string "//["
        case 99: // In <REGEX> Recognized '{OneLineCmnt}',	Shortest string "//{"
        case 100: // In <REGEX> Recognized '{OneLineCmnt}',	Shortest string "//\\"
        case 101: // In <REGEX> Recognized '{OneLineCmnt}',	Shortest string "//\""
        case 102: // In <REGEX> Recognized '{OneLineCmnt}',	Shortest string "//\"\\"
        case 103: // In <REGEX> Recognized '{OneLineCmnt}',	Shortest string "//{G"
        case 104: // In <REGEX> Recognized '{OneLineCmnt}',	Shortest string "//{8"
        case 105: // In <REGEX> Recognized '{OneLineCmnt}',	Shortest string "//{*"
        case 106: // In <REGEX> Recognized '{OneLineCmnt}',	Shortest string "//{8,"
        case 107: // In <REGEX> Recognized '{OneLineCmnt}',	Shortest string "//[/"
        case 108: // In <REGEX> Recognized '{OneLineCmnt}',	Shortest string "//[\\"
return (int)Tokens.csCommentL;
            break;
        case 15: // Recognized '^{CmntStrt}{ABStar}\**',	Shortest string "^/*"
        case 16: // Recognized '^{CmntStrt}{ABStar}\**',	Shortest string "^/**"
yy_push_state(CMMNT); 
                         comStart = TokenSpan(); 
                         return (int)Tokens.defCommentS;
            break;
        case 17: // Recognized '^{CmntStrt}{ABStar}\**{CmntEnd}',	Shortest string "^/**/"
return (int)Tokens.defCommentE;
            break;
        case 19: // In <SKIP> Recognized '{DotChr}+',	Shortest string "/"
        case 20: // In <SKIP> Recognized '{DotChr}+',	Shortest string "["
yy_pop_state();
            break;
        case 21: // In <RULES> Recognized '^{NotWh}',	Shortest string "^/"
        case 22: // In <RULES> Recognized '^{NotWh}',	Shortest string "^["
        case 23: // In <RULES> Recognized '^{NotWh}',	Shortest string "^%"
yy_push_state(REGEX); 
                       yyless(0);
            break;
        case 24: // In <RULES> Recognized '^<',	Shortest string "^<"
yy_push_state(REGEX); 
                       yy_push_state(NMLST); 
                       return (int)Tokens.lCond;
            break;
        case 25: // In <RULES> Recognized '^"<<EOF>>"',	Shortest string "^<<EOF>>"
yy_push_state(SMACT); 
                       yy_push_state(SPACE); 
                       return (int)Tokens.pattern;
            break;
        case 26: // In <RULES> Recognized '{CmntStrt}{ABStar}\**',	Shortest string "/*"
        case 27: // In <RULES> Recognized '{CmntStrt}{ABStar}\**',	Shortest string "/**"
yy_push_state(CMMNT);
                       comStart = TokenSpan(); 
                       return (int)Tokens.csCommentS;
            break;
        case 28: // In <RULES> Recognized '{CmntStrt}{ABStar}\**{CmntEnd}',	Shortest string "/**/"
return (int)Tokens.csCommentE;
            break;
        case 30: // In <UCODE> Recognized '{CShOps}',	Shortest string "/"
        case 34: // In <UCODE> Recognized '{CShOps}',	Shortest string "^%"
        case 35: // In <UCODE> Recognized '{CShOps}',	Shortest string "@"
        case 39: // In <UCODE> Recognized '{CShOps}',	Shortest string ">"
        case 42: // In <UCODE> Recognized '{CShOps}',	Shortest string "-"
        case 43: // In <UCODE> Recognized '{CShOps}',	Shortest string "+"
        case 44: // In <UCODE> Recognized '{CShOps}',	Shortest string "#"
        case 45: // In <UCODE> Recognized '{CShOps}',	Shortest string "%"
        case 46: // In <UCODE> Recognized '{CShOps}',	Shortest string "<"
        case 58: // In <BCODE> Recognized '{CShOps}',	Shortest string "^%"
return (int)Tokens.csOp;
            break;
        case 31: // In <UCODE> Recognized '\[',	Shortest string "["
return (int)Tokens.csLBrac;
            break;
        case 32: // In <UCODE> Recognized '{Ident}',	Shortest string "G"
return (int)GetIdToken(yytext);
            break;
        case 33: // In <UCODE> Recognized '{Number}',	Shortest string "8"
return (int)Tokens.csNumber;
            break;
        case 36: // In <UCODE> Recognized '\{',	Shortest string "{"
return (int)Tokens.csLBrace;
            break;
        case 37: // In <UCODE> Recognized '\}',	Shortest string "}"
return (int)Tokens.csRBrace;
            break;
        case 38: // In <UCODE> Recognized ',',	Shortest string ","
return (int)Tokens.comma;
            break;
        case 41: // In <UCODE> Recognized '\]',	Shortest string "]"
return (int)Tokens.csRBrac;
            break;
        case 48: // In <UCODE> Recognized ';',	Shortest string ";"
return (int)Tokens.semi;
            break;
        case 49: // In <UCODE> Recognized '\.',	Shortest string "."
return (int)Tokens.csDot;
            break;
        case 50: // In <UCODE> Recognized '\(',	Shortest string "("
return (int)Tokens.csLPar;
            break;
        case 51: // In <UCODE> Recognized '\)',	Shortest string ")"
return (int)Tokens.csRPar;
            break;
        case 52: // In <UCODE> Recognized '{LitChr}',	Shortest string "'/'"
return (int)Tokens.csLitchr;
            break;
        case 53: // In <UCODE> Recognized '{BadStr}',	Shortest string ""
        case 54: // In <UCODE> Recognized '{BadStr}',	Shortest string "\"\r"
Error(102, TokenSpan()); 
                       return (int)Tokens.repErr;
            break;
        case 55: // In <UCODE> Recognized '{LitStr}',	Shortest string "\"\""
return (int)Tokens.csLitstr;
            break;
        case 56: // In <UCODE> Recognized '{VerbStr}',	Shortest string "@\"\""
return (int)Tokens.csVerbstr;
            break;
        case 57: // In <UCODE> Recognized '^%\}',	Shortest string "^%}"
yy_pop_state(); yy_push_state(XPEOL); return (int)Tokens.rPcBrace;
            break;
        case 59: // In <BCODE> Recognized '\{',	Shortest string "{"
depth++; return (int)Tokens.csLBrace;
            break;
        case 60: // In <BCODE> Recognized '\}',	Shortest string "}"
if (depth > 0) { depth--; return (int)Tokens.csRBrace; }
                            else           { yy_pop_state(); return (int)Tokens.lxRBrace; }
            break;
        case 61: // In <LCODE> Recognized '{Eol}',	Shortest string ""
        case 62: // In <LCODE> Recognized '{Eol}',	Shortest string "\r"
yy_pop_state(); ResetBadCount(); return (int)Tokens.EOL;
            break;
        case 63: // In <INDNT> Recognized '^{NotWh}{DotChr}*',	Shortest string "^/"
        case 64: // In <INDNT> Recognized '^{NotWh}{DotChr}*',	Shortest string "^["
        case 65: // In <INDNT> Recognized '^{NotWh}{DotChr}*',	Shortest string "^@"
        case 66: // In <INDNT> Recognized '^{NotWh}{DotChr}*',	Shortest string "^\""
        case 67: // In <INDNT> Recognized '^{NotWh}{DotChr}*',	Shortest string "^\"\\"
        case 68: // In <INDNT> Recognized '^{NotWh}{DotChr}*',	Shortest string "^@\""
yy_pop_state(); yyless(0); return (int)Tokens.lxEndIndent;
            break;
        case 69: // In <CMMNT> Recognized '{ABStar}\**',	Shortest string ""
        case 70: // In <CMMNT> Recognized '{ABStar}\**',	Shortest string "^"
        case 71: // In <CMMNT> Recognized '{ABStar}\**',	Shortest string "/"
        case 72: // In <CMMNT> Recognized '{ABStar}\**',	Shortest string "["
        case 73: // In <CMMNT> Recognized '{ABStar}\**',	Shortest string "^\t"
        case 74: // In <CMMNT> Recognized '{ABStar}\**',	Shortest string "^%"
        case 75: // In <CMMNT> Recognized '{ABStar}\**',	Shortest string "*"
return (int)Tokens.csCommentS;
            break;
        case 76: // In <CMMNT> Recognized '{ABStar}\**{CmntEnd}',	Shortest string "*/"
yy_pop_state(); return (int)Tokens.csCommentE;
            break;
        case 78: // In <SMACT> Recognized '{Eol}',	Shortest string ""
        case 81: // In <SMACT> Recognized '{Eol}',	Shortest string "\r"
yy_pop_state(); 
                       Error(89, TokenSpan()); 
                       return (int)Tokens.csOp;
            break;
        case 79: // In <SMACT> Recognized '{NotWh}',	Shortest string "/"
        case 80: // In <SMACT> Recognized '{NotWh}',	Shortest string "["
        case 82: // In <SMACT> Recognized '{NotWh}',	Shortest string "^%"
yy_pop_state(); 
                       yy_push_state(LCODE); 
                       yyless(0);
            break;
        case 83: // In <SMACT> Recognized '\{',	Shortest string "{"
yy_pop_state(); 
                       yy_push_state(BCODE); 
                       depth = 0; 
                       return (int)Tokens.lxLBrace;
            break;
        case 84: // In <SMACT> Recognized '\|',	Shortest string "|"
yy_pop_state(); return (int)Tokens.lxBar;
            break;
        case 85: // In <XPEOL> Recognized '{NotWh}{DotChr}*',	Shortest string "/"
        case 86: // In <XPEOL> Recognized '{NotWh}{DotChr}*',	Shortest string "["
Error(80, TokenSpan()); return (int)Tokens.repErr;
            break;
        case 87: // In <REGEX> Recognized '{Regex}+',	Shortest string "/"
        case 89: // In <REGEX> Recognized '{Regex}+',	Shortest string "G"
        case 90: // In <REGEX> Recognized '{Regex}+',	Shortest string "^%"
yy_pop_state();
                       switch (YY_START) {
                           case INITIAL:
                               yy_push_state(XPEOL); break;
                           case RULES:
                           case PRGRP:
                               yy_push_state(SMACT);
                               yy_push_state(SPACE); break;
                       } 
                       return (int)Tokens.pattern;
            break;
        case 91: // In <REGEX> Recognized '\{',	Shortest string "{"
yy_pop_state();
                       if (YY_START == RULES || YY_START == PRGRP) {
                           yy_push_state(PRGRP);
                           yy_push_state(XPEOL);
                           return (int)Tokens.lxLBrace;
                       } else {
                           Error79(TokenSpan());
                           return (int)Tokens.repErr;
                       }
            break;
        case 94: // In <REGEX> Recognized '{Regex}*{BadStr}',	Shortest string ""
        case 95: // In <REGEX> Recognized '{Regex}*{BadStr}',	Shortest string "\"\r"
yy_pop_state();
                       Error(102, TokenSpan());
                       return (int)Tokens.repErr;
            break;
        case 109: // In <NMLST> Recognized '{Space}+',	Shortest string "^\t"
        case 116: // In <NMLST> Recognized '{Space}+',	Shortest string "\t"
/* skip */
            break;
        case 110: // In <NMLST> Recognized '{Ident}',	Shortest string "G"
return (int)Tokens.name;
            break;
        case 111: // In <NMLST> Recognized '{Number}',	Shortest string "8"
return (int)Tokens.csNumber;
            break;
        case 113: // In <NMLST> Recognized '\*',	Shortest string "*"
return (int)Tokens.csStar;
            break;
        case 114: // In <NMLST> Recognized ',',	Shortest string ","
return (int)Tokens.comma;
            break;
        case 115: // In <NMLST> Recognized '>',	Shortest string ">"
yy_pop_state(); 
                       return (int)Tokens.rCond;
            break;
        case 117: // In <SPACE> Recognized '{Eol}',	Shortest string ""
        case 121: // In <SPACE> Recognized '{Eol}',	Shortest string "\r"
yy_pop_state(); Error(78, TokenSpan()); return (int)Tokens.EOL;
            break;
        case 118: // In <SPACE> Recognized '{NotWh}+',	Shortest string "/"
        case 119: // In <SPACE> Recognized '{NotWh}+',	Shortest string "["
Error(78, TokenSpan()); return (int)Tokens.repErr;
            break;
        case 120: // In <SPACE> Recognized '{Space}+',	Shortest string "^\t"
        case 122: // In <SPACE> Recognized '{Space}+',	Shortest string "\t"
yy_pop_state();
            break;
        case 123: // In <VRBTM> Recognized '{DotChr}+',	Shortest string "/"
        case 124: // In <VRBTM> Recognized '{DotChr}+',	Shortest string "["
yy_pop_state(); return (int)Tokens.verbatim;
            break;
        case 125: // In <VRBTM> Recognized '{Space}+',	Shortest string "\t"
/* skip */
            break;
        case 126: // In <PRGRP> Recognized '{NotWh}',	Shortest string "/"
        case 127: // In <PRGRP> Recognized '{NotWh}',	Shortest string "["
        case 129: // In <PRGRP> Recognized '{NotWh}',	Shortest string "^%"
yy_push_state(REGEX); yyless(0);
            break;
        case 128: // In <PRGRP> Recognized '^{Space}+',	Shortest string "^\t"
/* skip */
            break;
        case 130: // In <PRGRP> Recognized '\}',	Shortest string "}"
yy_pop_state();
                       yy_push_state(XPEOL);
                       return (int)Tokens.lxRBrace;
            break;
        case 131: // In <PRGRP> Recognized '\<',	Shortest string "<"
yy_push_state(REGEX); 
                       yy_push_state(NMLST); 
                       return (int)Tokens.lCond;
            break;
        case 132: // In <PRGRP> Recognized '"<<EOF>>"',	Shortest string "<<EOF>>"
yy_push_state(SMACT); 
                       yy_push_state(SPACE); 
                       return (int)Tokens.pattern;
            break;
        default:
            break;
    }
#pragma warning restore 162, 1522
#endregion
                    }
                }
            } // end try
            finally {
// User-specified epilog to scan()
/* Epilog from LEX file */
	yylloc = new LexSpan(tokLin, tokCol, tokELin, tokECol, tokPos, tokEPos, buffer);
// End, user-specified epilog
            } // end finally
        }

#if BACKUP
        void SaveStateAndPos(ref Context ctx) {
            ctx.bPos  = buffer.Pos;
            ctx.rPos  = readPos;
            ctx.cCol  = cCol;
            ctx.lNum  = lNum;
            ctx.state = state;
            ctx.cChr  = code;
        }

        void RestoreStateAndPos(ref Context ctx) {
            buffer.Pos = ctx.bPos;
            readPos = ctx.rPos;
            cCol  = ctx.cCol;
            lNum  = ctx.lNum;
            state = ctx.state;
            code  = ctx.cChr;
        }
#endif  // BACKUP

        // ============= End of the tokenizer code ================

#if STACK        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal void yy_clear_stack() { scStack.Clear(); }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal int yy_top_state() { return scStack.Peek(); }
        
        internal void yy_push_state(int state)
        {
            scStack.Push(currentScOrd);
            BEGIN(state);
        }
        
        internal void yy_pop_state()
        {
            // Protect against input errors that pop too far ...
            if (scStack.Count > 0) {
				int newSc = scStack.Pop();
				BEGIN(newSc);
            } // Otherwise leave stack unchanged.
        }
 #endif // STACK

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal void ECHO() { Console.Out.Write(yytext); }
        
#region UserCodeSection

/*  User code is in ParseHelper.cs  */

#endregion
    } // end class $Scanner


} // end namespace
